import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
//import Image from 'next/image'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>H@ckDroid</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
          {/* ======================================= */}
          <section className="text-gray-400 bg-gray-900 body-font">
  <div className="container mx-auto flex px-5 py-24 md:flex-row flex-col items-center">
    <div className="lg:flex-grow md:w-1/2 lg:pr-24 md:pr-16 flex flex-col md:items-start md:text-left mb-16 md:mb-0 items-center text-center">
      <h1 className="title-font sm:text-4xl text-3xl mb-4 font-medium text-white">
      EVERYTHING ABOUT 
        <br className="hidden lg:inline-block" />
        ANDROID HACKING
      </h1>
      <p className="mb-8 leading-relaxed">
      verything About Android Hacking Is World Most Advance Course At Affordable Price. The Course Is Online You Cannot Download The Course In This Course You Will Learn Everything About Android Hacking As The Name Suggest, For Your Doubts/Problems We Have Created Private Whatsapp Group For Course Users, We Have to Make Course Less Theoretical More Practical So You Don’t Have To Worry Also You Can Request Any Topic That Our Course Don’t Have
      </p>
      <div className="flex justify-center">
        <button className="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg">
        PREVIEW THIS COURSE
        </button>
        {/* <button className="ml-4 inline-flex text-gray-400 bg-gray-800 border-0 py-2 px-6 focus:outline-none hover:bg-gray-700 hover:text-white rounded text-lg">
          Button
        </button> */}
      </div>
    </div>
    <div className="lg:max-w-lg lg:w-full md:w-1/2 w-5/6">

    <Image
     className="object-cover object-center rounded h-full w-full"
     // loader={myLoader}
      src="/image.png"
      alt="Picture of the author"
      width={700}
    // layout="fill"
      height={500}
    />
      {/* <img
        className="object-cover object-center rounded h-full w-full"
        alt="hero"
        src="https://courses.techvansh.in/wp-content/uploads/2020/10/LIGHTandroidhacking-banner-scaled-min-1-870x440.jpg"
      /> */}
    </div>
  </div>
</section>

          
{/* =========================================================================== */}
    </>
  )
}
